# create_github_release.ps1
# Creates a GitHub Release and attaches the APK to it, using only the GitHub REST API
# (no dependency on 'gh'). Requires the GITHUB_TOKEN environment variable to be set
# with a Personal Access Token that has the "repo" scope.

$ErrorActionPreference = "Stop"

$token = $env:GITHUB_TOKEN
if (-not $token) {
    Write-Host "ERROR: the GITHUB_TOKEN environment variable is not set." -ForegroundColor Red
    Write-Host "Set it once with: setx GITHUB_TOKEN ""<your-personal-access-token>""" -ForegroundColor Yellow
    Write-Host "(then reopen PowerShell so the variable gets picked up)" -ForegroundColor Yellow
    exit 1
}

$remoteUrl = git remote get-url origin
if (-not $remoteUrl) {
    Write-Host "ERROR: no 'origin' remote configured." -ForegroundColor Red
    exit 1
}

if ($remoteUrl -match "github\.com[:/](?<owner>[^/]+)/(?<repo>[^/.]+)") {
    $owner = $matches['owner']
    $repo  = $matches['repo']
} else {
    Write-Host "ERROR: could not determine owner/repo from remote '$remoteUrl'." -ForegroundColor Red
    exit 1
}

$apkPath = "build\app\outputs\flutter-apk\app-default-release.apk"
if (-not (Test-Path $apkPath)) {
    Write-Host "ERROR: could not find the APK at $apkPath." -ForegroundColor Red
    exit 1
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$tag = "build-$timestamp"

$headers = @{
    Authorization = "Bearer $token"
    Accept        = "application/vnd.github+json"
}

$body = @{
    tag_name = $tag
    name     = "Sossoldi 32-bit - build $timestamp"
    body     = "Automated build generated by update_sossoldi.bat."
} | ConvertTo-Json

Write-Host "Creating release $tag on $owner/$repo..." -ForegroundColor Cyan

try {
    $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$owner/$repo/releases" `
        -Method Post -Headers $headers -Body $body -ContentType "application/json"
} catch {
    Write-Host "ERROR while creating the release: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

$uploadUrl = ($release.upload_url -replace '\{.*\}', '') + "?name=app-default-release.apk"

Write-Host "Uploading the APK..." -ForegroundColor Cyan

try {
    Invoke-RestMethod -Uri $uploadUrl -Method Post -Headers $headers `
        -InFile $apkPath -ContentType "application/vnd.android.package-archive" | Out-Null
} catch {
    Write-Host "WARNING: release created but APK upload failed: $($_.Exception.Message)" -ForegroundColor Yellow
    exit 1
}

Write-Host "Release $tag published with the APK attached." -ForegroundColor Green
exit 0